#!name=定点范围20250416-1
#!desc=可以修改特定软件的范围
[Rule]
DOMAIN-KEYWORD,patentexam,DIRECT

[URL Rewrite]
^https:\/\/app2.patentexam.com.* direct

[Script]
usecar=type=http-response,pattern=https://app.patentexam.com.cn/prod-api/business/attendance_location/selectEnabledLocations,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ilzge/usecarmod/refs/heads/main/xinusecar.js,script-update-interval=600

[MITM]
hostname = %APPEND% *.patentexam.com.cn


