#!name=定点范围20260325
#!desc=可以修改特定软件的范围
[Rule]
DOMAIN-KEYWORD,patentexam,DIRECT

[Script]
usecar = type=http-response,pattern=https://app.patentexam.com.cn/prod-api/business/attendance_location/selectEnabledLocations,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ilzge/usecarmod/refs/heads/main/xinusecarrocket/xinusecar.js,script-update-interval=600

random = type=http-request,pattern=https://app.patentexam.com.cn/prod-api/business/attendance_record/punch,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ilzge/usecarmod/refs/heads/main/xinusecarrocket/xinusecarrandom.js,script-update-interval=600

[MITM]
hostname = %APPEND% *.patentexam.com.cn
